receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/jaeger:
    endpoint: "https://jaeger:4317"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
