global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'backend:8000'
        labels:
          app: backend